---
title: "Statistical rare variant analysis for autism"
output:
  html_document:
    toc: false
---


[This is the project][project]


## MIRAGE with logistic prior 

* [modeling with logistic prior](model_logistic_prior.html)
* [simulation experiments](simulation_logistic_prior.html)

   - additional simulations

 
## Simulation studies  
 
* [numerical simulation studies](simulation-study.html) 
* [effect of case control ratio](effect_case_control_ratio.html)
* [Figures](Figures.html)

## Whole exome sequencing (WES) data analysis for old sample  

* [Quality control (QC)](ASD.html)


* [Variant Set (VS) analysis](variant_set_analysis.html)

* [Gene set analysis](GeneSetAnalysis.html)


## Cell data downloaded from dbGaP 


* [analysis for ASD data dowloaded from dbGaP](ASD_dbGaP.html) 
 
* [analysis for Schizophrenia data](SCZ-analysis.html) 

* [code for merging annotation features and sample data from dbGap](ASD_dbGaP_code.html)


## Analysis for transmitted variants from ASC cell paper 

* [Quality control (QC) and annotate variants in Cell data](ASC_cell_data.html)

* [Variant set (VS) analysis for transmitted variants in ASC cell paper](VS-ASC.html)

* [Gene set analysis for transmitted variants in ASC cell paper](gene_set_analysis_cell_data.html)


## Analysis for transmitted variant from new (unpublished) sample 

* [Quality control (QC) for new sample](ASC_new_sample.html)

* [Synonymous variants](ASC_new_sample_syn_var.html)

* [Variant set (VS) analysis](ASC_new_sample_variant_set.html)

* [gene set analsyis for new sample](ASC_new_sample_gene_set.html)

* [Kyle's variants](variant_from_kyle.html)

* [liftover samples](liftover_files.html)

* [STAAR analysis](staar_analysis.html)

###  [Laura's result](Laura_analysis.html)

* [QQ plot of burden and ACAT](qqplot_burden_acat.html)

* [how correlated variants influence MIRAGE results](correlated_variants_analysis.html)



[project]: https://www.dropbox.com/home/RareVariantProject?preview=RareVariant.pdf
[rmarkdown]: http://rmarkdown.rstudio.com/rmarkdown_websites.htm
[rstudio]: https://www.rstudio.com/products/rstudio/download/preview/
